In [1]:
import pandas as pd

In [25]:
todas_redes = pd.read_csv('Epanet\\Brazlândia\\rede brazlandia.csv',index_col=False)
todas_redes

C:\Users\filipe_silva\AppData\Local\Temp\ipykernel_43608\4147352519.py:1: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  todas_redes = pd.read_csv('Epanet\\Brazlândia\\rede brazlandia.csv',index_col=False)

        ID Node1 Node2     Length  Diameter  Roughness  MinorLoss Status;
0        0  1272  1266  41.412884        60        137          0    Open
1        1   509  2568   4.608553        60        137          0    Open
2        2  2566  2567   3.410830        60        137          0    Open
3        4  2754  2640  75.732263        50         50          0    Open
4        6  1813  2734  34.226609       150        131          0    Open
...    ...   ...   ...        ...       ...        ...        ...     ...
3111   155   564  2251   8.849000        60        135          0    Open
3112   156   564  2252   8.195900        60        135          0    Open
3113   215   835   976  38.810000        60        132          0    Open
3114   216  2014  2015   3.950000       110        132          0    Open
3115  1065  2220  2029   0.100000       160        135          0    Open

[3116 rows x 8 columns]

In [23]:
coord = pd.read_csv('Epanet\\Brazlândia\\coordenadas.csv',index_col=False)
coord

             Node     X-Coord      Y-Coord
0               1  156576.391  8263416.779
1               3  156573.435  8263504.313
2               4  156738.555  8263506.399
3               5  156738.926  8263527.869
4               6  156739.480  8263549.500
...           ...         ...          ...
2747          973  157991.579  8263994.460
2748          976  156894.220  8265491.631
2749  ERE.BRZ.001  157859.253  8265770.058
2750  RAP.BRZ.001  157860.740  8265778.978
2751  EBO.BRZ.001  157858.037  8265782.357

[2752 rows x 3 columns]

In [ ]:
merge1 = pd.merge(todas_redes,coord,left_on="Node1",right_on='Node',how="inner")
merge2 = pd.merge(todas_redes,coord,left_on="Node2",right_on='Node',how="inner")

,ID,Node1,Node2,Length,Diameter,Roughness,MinorLoss,Status;,Node,X-Coord,Y-Coord
0,0,1272,1266,41.412884,60,137,0,Open,1272,157057.524,8265563.296
1,1,509,2568,4.608553,60,137,0,Open,509,157620.471,8265502.467
2,2,2566,2567,3.410830,60,137,0,Open,2566,157517.090,8265511.555
3,4,2754,2640,75.732263,50,50,0,Open,2754,156882.928,8263163.892
4,6,1813,2734,34.226609,150,131,0,Open,1813,156808.518,8263213.116
...,...,...,...,...,...,...,...,...,...,...,...
3111,155,564,2251,8.849000,60,135,0,Open,564,157142.989,8266550.740
3112,156,564,2252,8.195900,60,135,0,Open,564,157142.989,8266550.740
3113,215,835,976,38.810000,60,132,0,Open,835,156896.177,8265457.837
3114,216,2014,2015,3.950000,110,132,0,Open,2014,157026.688,8264726.237
3115,1065,2220,2029,0.100000,160,135,0,Open,2220,157026.642,8264714.975